def label_to_categories():
    return { 
        "restaurant": [ "Food", "Dining out" ],
        "fika": [ "Food", "Fika" ],
        "music-streaming": [ "Streaming", "Music" ],
        "video-streaming": [ "Streaming", "Video" ],
        "groceries": [ "Food", "Groceries" ],
        "sports": [ "Healthcare", "Sports" ],
        "concert": [ "Leisure", "Concerts" ],
        "cinema": [ "Leisure", "Cinema" ],
        "home-others": [ "Homeneeds", "Others" ],
        "taxi": [ "Automobile", "Taxi" ],
        "fuel": [ "Automobile", "Gas" ],
        "parking": [ "Automobile", "Parking" ],
        "shared-car": [ "Automobile", "Shared" ],
        "medicine": [ "Healthcare", "Prescription" ],
        "amazon": [ "Shopping", "Amazon" ],
        "medic": [ "Healthcare", "Physician" ],
        "shopping-misc": [ "Shopping", "Misc" ],
        "membership": [ "Donation", "Membership" ],
        "cloud-storage": [ "Cloud", "Storage" ],
        "donation": [ "Donation", "" ],
        "charity": [ "Donation", "Charity" ],
        "clothes": [ "Shopping", "Clothes" ],
        "bills": [ "Bills", "" ],
        "videogames": [ "Leisure", "eGames" ],
        "vacation": [ "Vacation", "Travel" ],
        "rolezinho": [ "Leisure", "Rolezinho" ],
        "pets-health": [ "Pets", "Healthcare" ],
        "pets-food": [ "Pets", "Food" ],
        "pets-other": [ "Pets", "Other" ],
        "birita": [ "Leisure", "Birita" ],
        "busao": [ "Transport", "Public" ],
        "news": [ "Education", "News" ],
        "courses": [ "Education", "Others" ],
        "moneyex": [ "Transfer", "Exchange" ],
        "job-insurance": [ "Job", "Insurance" ],
        "union": [ "Job", "Union" ],
        "salary": [ "Income", "Salary" ],
        "banks": [ "Bills", "Bank" ],
        "mortgage": [ "Bills", "Mortgage" ],
    #    "": [ "", "" ],
    #    "": [ "", "" ],
    #    "": [ "", "" ],
    }

def list_invalid_payees():
    return [
        "BETALT BG DATUM*",
        "Betalning BG 595-4300 SAS EUROBONUS",
    ]

def payee_to_labels():
    return {
        "[.]*PRESSBYRAN": "fika",
        "60 MINUTOS[.]*": "vacation",
        "7-ELEVEN*": "fika",
        "800 GRADER PIZZA": "restaurant",
        "ABA ÖGONKLINIK": "medic",
        "ACAI[ ]+[.]*\*?EMPORIO MANAIR": "restaurant",
        "AFC HOTELARIA LTDA": "vacation",
        "AFOUND* OTHER STORIES": "clothes",
        "AFTER PUB BESSA": "restaurant",
        "AG AUTOCLEAN": "vacation",
        "ÅKESHOVS SIM": "sports",
        "ALNAFFIE AB": "home-others",
        "ALOHA ACAI": "restaurant",
        "ALTAR COZINHA ANCESTRA": "restaurant",
        "AMAZING ASIAN WOK": "restaurant",
        "AMAZONMKTPLC*": "shopping-misc",
        "AMIDA KOLGRILL": "restaurant",
        "AM STORE": "fika",
        "AMZN[.]*": "amazon",
        "ANALISIS LABORATORIO": "medic",
        "APOTEA": "medicine",
        "APOTEK[.]*": "medicine",
        "AREAS PORTUGAL SA": "vacation",
        "AREZZO": "shopping-misc",
        "ARIRANG": "restaurant",
        "ÅRSAVGIFT": "bills",
        "BABAS": "restaurant",
        "BARCELONA COMERCIO VAR": "vacation",
        "BAUHAUS": "home-others",
        "BAZARENS ISBUTIK": "shopping-misc",
        "BERCY BOA VIAGEM": "restaurant",
        "BIKESTER": "sports",
        "BLOMSTERLANDET": "home-others",
        "BOB'S": "fika",
        "BOFF BURGERBAR SYDHAVN": "restaurant",
        "BOLT.EU[.]*": "taxi",
        "BONNA GELATERIA": "fika",
        "BONNIER-DN": "news",
        "BR¦D & SALT BAG": "fika",
        "BREWDOG S:T ERI": "restaurant",
        "BROMMAPLANS VARDCENTRA": "medic",
        "BROMMATORG FRUKT O GRO": "groceries",
        "BURGER KING ZH": "restaurant",
        "BV3 VESTUARIOS LTDA": "clothes",
        "CAFE FIX": "fika",
        "CA JA ALIMENTACAO": "restaurant",
        "CALZEDONIA SPA": "vacation",
        "CASA DE NARA": "restaurant",
        "CDON[.]*": "shopping-misc",
        "CHALET SUISSE": "restaurant",
        "CHOCOLATE SETE COLINAS": "fika",
        "CHOPCHOP ENKOPI": "restaurant",
        "CHURRASCARIA E LANCHO": "restaurant",
        "CIRCLE K[.]*": "fuel",
        "CLAS OHLSON": "home-others",
        "COELHOS MESA": "restaurant",
        "COLEGIO ND LANCHONETE": "fika",
        "COOP ": "groceries",
        "CROWDFARMING": "groceries",
        "DECATHLON SVERIGE": "sports",
        "DELTA AERO FORTALEZA 2": "fika",
        "DE LUXE MUSIC": "shopping-misc",
        "D{RMED PASTA HB L}NGHO": "restaurant",
        "DROGASIL": "medicine",
        "DUAS": "clothes",
        "DULCE TENTACION STOCKH": "fika",
        "EDBLAD & CO AB": "shopping-misc",
        "EDELWEISS CAFE & BISTR": "restaurant",
        "EL CHEFE BARBERSHOP": "shopping-misc",
        "EMILY SAMPAIO": "clothes",
        "ENCANTOS DE CLARA": "rolezinho",
        "ESPACO CREATIVE": "medicine",
        "ESPRESSO H 219": "fika",
        "ESTALEIRO RESTAURANTE": "restaurant",
        "ESTAPAR AERO JPA": "vacation",
        "ESUKI SUSHI[.]*": "restaurant",
        "EXTRAKORTSAVGIFT": "bills",
        "FABIO BEACH BAR": "restaurant",
        "FABRIQUE": "groceries",
        "FE SOLUCAO": "clothes",
        "FILMSTADEN SCAN": "cinema",
        "FIT HOTEIS E SERVICOS": "vacation",
        "FIVE MOMENTS AB": "restaurant",
        "FLOWBIRD APP": "parking",
        "FOETEX FOOD KR BERNIKO": "restaurant",
        "FOODORA AB": "restaurant",
        "FOREX ATM 2204 T5 PIR": "moneyex",
        "FORMAGGIO RESTAURANTE": "restaurant",
        "FROMAGERIET": "groceries",
        "FROZEN FACTORY V{LLING": "fika",
        "FULLANO PRAIA": "restaurant",
        "GATEAU CENTRALEN": "fika",
        "GATE RETAIL TAP": "vacation",
        "[.]*GELATO SCARFO[.]*": "fika",
        "GEORGIEN HOUSE": "restaurant",
        "GIRO PIZZA AB": "restaurant",
        "GLOBEARENA": "vacation",
        "GOLFINHOS BAR E RESTAU": "restaurant",
        "GOOGLE PAYMENT IE LTD": "shopping-misc",
        "GOOGLE PLAY*": "shopping-misc",
        "GOOGLE[ ]+\*YOUTUBE MEMBER": "membership",
        "GRAND HOTEL RESTAURANG": "restaurant",
        "HAPPY WS": "clothes",
        "HÅRSTUDIO 08 ST": "shopping-misc",
        "HEMKÖP ": "groceries",
        "HIJA DE SANCHEZ": "restaurant",
        "H M": "clothes",
        "HM SE0141": "shopping-misc",
        "HMSHOST ARLANDA AIRPOR": "vacation",
        "HV SHOP MANAIRA": "parking",
        "IBIS RECIFE AEROPORTO": "vacation",
        "[.]*ICA[.]*": "groceries",
        "IKEA GALLERIAN": "fika",
        "INDIAN GARDEN": "restaurant",
        "JERFELLA DJURKLINIK": "pets-health",
        "JOEANDTHEJUICE": "fika",
        "JRDM SHOPPING RECIFE": "medicine",
        "KANAANS": "fika",
        "KIAN KITCHEN AB": "restaurant",
        "KICKS 805 VELLINGBY": "clothes",
        "KINTO SHARE SWEDEN": "shared-car",
        "KJELL & CO 25": "home-others",
        "KJELL & CO 90": "shopping-misc",
        "K KARAOKE": "rolezinho",
        "KLARNA\*COOP.SE": "shopping-misc",
        "KOTTKOMPANIET I STOCKH": "groceries",
        "KRONANS APOTEK": "medicine",
        "LA BELLE": "vacation",
        "LAGERHAUS ": "home-others",
        "LA NETA": "restaurant",
        "LAUNDRY HOME": "vacation",
        "LIDL 264 / STHLM VELLI": "groceries",
        "LILIA COMERCIO VAREJIS": "clothes",
        "LINDEX": "clothes",
        "LIZA LANGEN FLOWERS": "shopping-misc",
        "LYKO.COM/SV": "shopping-misc",
        "MAG ADMINISTRACAO DE N": "vacation",
        "MANS OLS UTVERDSHUS": "vacation",
        "MARE ALTA RESTAURANTE": "restaurant",
        "MASSIMODUTTI.COM": "courses",
        "MAT VID SILJAN": "restaurant",
        "MOXY COPENHAGEN": "vacation",
        "MYRORNA": "clothes",
        "NAGEM INFORMATICA": "shopping-misc",
        "NAKED JUICEBAR": "fika",
        "NAWABI KITCHEN AB": "restaurant",
        "NETFLIX.COM": "video-streaming",
        "NETS\*LEKSAND SOMMARL": "vacation",
        "OHLSSONS TYGER": "home-others",
        "OKQ8": "fuel",
        "OLEARYS": "restaurant",
        "OOGLE[ ]+\*GOOGLE PLAY AP": "shopping-misc",
        "OSTERQVIST DELIKATESSE": "groceries",
        "PADARIA UNIPAO TAMBAU": "fika",
        "PADOCA DO CICICO": "fika",
        "PAG\*BOIEBRASA": "restaurant",
        "PAG\*CASADOSFRIOS": "fika",
        "PAG\*DELTAEXPRESSO[.]*": "fika",
        "PAG\*DUETTO02": "home-others",
        "PAG\*FRISABOR": "fika",
        "PAG\*LOPESEPEREIRALTDA": "taxi",
        "PAG\*MARIAFATIMA": "restaurant",
        "PAG\*NAEVNTOS": "fika",
        "PAG\*OREIDASCOXINHAS": "restaurant",
        "PAG\*PATRICIAMARIADASI": "home-others",
        "PAG\*POSTOJR": "fuel",
        "PAG\*POSTOVIP": "fuel",
        "PAG\*SENAC": "shopping-misc",
        "PAG\*SOSOTORRINO": "medic",
        "PAG\*TADEURAMALHO": "restaurant",
        "PAGUE MENOS[.]*": "medicine",
        "PANDA SUSHI WOK DUMPLI": "restaurant",
        "PASTEL DA PRAIA JP": "restaurant",
        "PAYPAL[ ]+\*CASARCOM": "shopping-misc",
        "PAYPAL[ ]+\*EASYPARK AB": "parking",
        "PAYPAL[ ]+\*EBAY US": "shopping-misc",
        "PAYPAL[ ]+\*HORNBACH SE": "home-others",
        "PAYPAL[ ]+\*PATREON": "membership",
        "PAYPAL[ ]+\*PIAUI": "membership",
        "PAYPAL[ ]+\*STEAM GAMES": "videogames",
        "PAYPAL[ ]+\*THOMANN": "shopping-misc",
        "PAYPAL[ ]+\*X.": "shopping-misc",
        "PG \*KAIRO INNAAK KAIRO": "clothes",
        "PG \*TON CONCREFLORA": "shopping-misc",
        "PG \*TON LUCIANO DE S": "rolezinho",
        "P-HUS NORRA REAL": "parking",
        "PONTO DO ACAI": "restaurant",
        "PORTO FELIZ INDUSTRIA": "fika",
        "POSTO EXPRESSAO": "fuel",
        "PROSHOP.SE": "shopping-misc",
        "PUB ANCHOR-VEEM": "restaurant",
        "PURO ACAI": "restaurant",
        "QUINA DO FUTURO": "restaurant",
        "RACKSTA KIOSK": "fika",
        "RC COM DE ALIMENTOS": "groceries",
        "REDEPHARMA": "medicine",
        "REI DAS CARNES": "groceries",
        "RELOAD SUPERFOODBAR": "fika",
        "RESTAURANG AG": "restaurant",
        "RESTAURANG FORTUNATO A": "restaurant",
        "RESTAURANTE MANGAI": "restaurant",
        "RESTAURANT FELIX AUST": "restaurant",
        "RESTAURANT SELM": "restaurant",
        "RESULTHA TREINOS": "sports",
        "RÖDA HUSET": "birita",
        "ROYAL ARENA": "concert",
        "SE0142": "restaurant",
        "SECOND HAND VÄL": "shopping-misc",
        "SENSHI SUSHIBAR": "restaurant",
        "SHARETHEMEAL WFP": "membership",
        "SLAKTKYRKAN": "shopping-misc",
        "SL": "busao",
        "SNA. A.VER STOCKHOLM": "fika",
        "SOUTH HARBOUR CAFE": "fika",
        "SPOTIFY[.]*": "music-streaming",
        "STOCKHOLMS DJURKLINIK": "pets-health",
        "STROMMINGVAGNEN": "restaurant",
        "SUMMERBIRD CHOCOLATERI": "fika",
        "SUMUP\*ESTUDIO PRAIA": "concert",
        "SUNDBYBERGSKLINIKEN": "pets-health",
        "SUNDBYBERGS SPORTBAR A": "restaurant",
        "SUPERMERCADINHOS SAO L": "groceries",
        "SUPERMERCADO BEM MAIS": "groceries",
        "SUPERMERCADO COMETA E": "groceries",
        "SYSTEMBOLAGET": "birita",
        "T8NG HORNSGATA": "birita",
        "TABUA DE CARNE RESTAUR": "restaurant",
        "TAXI STOCKHOLM": "taxi",
        "THE COFFEE COLLECTIVE": "fika",
        "THELINS SUNDBYBERG": "fika",
        "TICKETMASTE": "concert",
        "TICKSTER.COM": "concert",
        "TIVOLI INDGANGE": "vacation",
        "TRESORIT": "cloud-storage",
        "UBER[ ]+\*EATS": "restaurant",
        "UBER[ ]*\*TRIP": "taxi",
        "UNIDAS LOCADORA[.]*": "shared-car",
        "VARANDA REST & PIZZ": "restaurant",
        "VASTERORT TRAFIKSKOLA": "courses",
        "VERD FRUT MANAIRA": "groceries",
        "VETE-KATTEN": "fika",
        "WALKTHROUGH LEVEL 1 ZR": "restaurant",
        "WAYNES COFFEE": "fika",
        "WIKIPEDIA": "donation",
        "WISE": "charity",
        "W\*MEDS.COM": "medic",
        "WOKHOUSE": "restaurant",
        "WOLT": "restaurant",
        "WWW.NETONNET.SE": "shopping-misc",
        "WWW ZALANDO SE": "shopping-misc",
        "XIA JING AB": "restaurant",
        "ZOOLOGISCHER GARTEN": "pets-other",
        "ZTL*LETIZ GELATO": "fika",
# nordea cathegories
        "Autogiro AGRIA": "pets-health",
        "Autogiro K\*Adlibris A": "shopping-misc",
        "Autogiro K\*Apotea AB": "medicine",
        "Autogiro K\*Crema": "fika",
        "Autogiro K\*XXL Sport": "sports",
        "Autogiro Nordicwell": "sports",
        "Autogiro OP SMILE": "membership",
        "Autogiro TELIA": "bills",
        "Autogiro T Hedvig[.]*": "home-others",
        "Autogiro UNHCR": "membership",
        "Autogiro UNION.AKASSA": "job-insurance",
        "Autogiro UNIONEN": "union",
        "Autogiro WSPA SVERIGE": "membership",
        "Lön": "salary",
        "Nordea Vardagspaket": "banks",
        "Omsättning lån 3992 46 77900": "mortgage",
        "Omsättning lån 3992 46 77919": "mortgage",
        "Swish betalning AB STORSTOCKHOLMS L": "busao",
        "Swish betalning BORGES DE OLIVEIRA": "rolezinho",
        "Swish betalning CASTELO BRANCO LEIT": "rolezinho",
        "Swish betalning ESPRESSO HOUSE SWED": "fika",
        "Swish betalning HUNDAR UTAN HEM": "pets-other",
        "Swish betalning Khaled Alzghoul": "home-others",
        "Swish betalning KLARNA BANK AB": "shopping-misc",
        "Swish betalning LILIAN GOUVEA FERNA": "rolezinho",
        "Swish betalning MELO DOS SANTOS RUG": "rolezinho",
        "Swish betalning MONTEIRO DE OLIVEIR": "rolezinho",
        "Swish betalning NETONNET AB": "shopping-misc",
        "Swish betalning ORNELAS DOS SANTOS": "rolezinho",
        "Swish betalning PIRES RIBEIRO SILVA": "rolezinho",
        "Swish betalning PRISCILA COSTA DA R": "rolezinho",
        "Swish betalning SF Anytime AB": "cinema",
        "Swish betalning SIGTUNA GELATO AB": "fika",
        "Swish inbetalning Angelo Nunes Trug": "rolezinho",
        "Swish inbetalning BORGES DE OLIVEIR": "rolezinho",
        "Swish inbetalning CASTELO BRANCO LE": "rolezinho",
        "Swish inbetalning DE MELLO PUSSENTE": "rolezinho",
        "Swish inbetalning ERIK GULLIKSSON": "rolezinho",
        "Swish inbetalning LILIAN GOUVEA FER": "rolezinho",
        "Swish inbetalning MONTEIRO DE OLIVE": "rolezinho",
        "Swish inbetalning PIRES RIBEIRO SIL": "rolezinho",
    #    "": "",
    #    "": "",
    #    "": "",
    #    "": "",
    } 

