def label_to_categories():
    return { 
        "restaurant": [ "Food", "Dining out" ],
        "fika": [ "Food", "Fika" ],
        "music-streaming": [ "Streaming", "Music" ],
        "video-streaming": [ "Streaming", "Video" ],
        "groceries": [ "Food", "Groceries" ],
        "sports": [ "Healthcare", "Sports" ],
        "concert": [ "Leisure", "Concerts" ],
        "cinema": [ "Leisure", "Cinema" ],
        "home-others": [ "Homeneeds", "Others" ],
        "taxi": [ "Automobile", "Taxi" ],
        "medicine": [ "Healthcare", "Prescription" ],
        "amazon": [ "Shopping", "Amazon" ],
        "medic": [ "Healthcare", "Physician" ],
        "shopping-misc": [ "Shopping", "Misc" ],
        "membership": [ "Donation", "Membership" ],
        "cloud-storage": [ "Cloud", "Storage" ],
        "donation": [ "Donation", "" ],
        "charity": [ "Donation", "Charity" ],
        "clothes": [ "Shopping", "Clothes" ],
        "bills": [ "Bills", "" ],
    #    "": [ "", "" ],
    #    "": [ "", "" ],
    }

def payee_to_labels():
    return { 
        "SPOTIFY": "music-streaming",
        "OLEARYS": "restaurant",
        "FABRIQUE": "groceries",
        "CAFE FIX": "fika",
        "ÅKESHOVS SIM": "sports",
        "TICKETMASTE": "concert",
        "UBER[ ]+\*EATS": "restaurant",
        "OSTERQVIST DELIKATESSE": "groceries",
        "OHLSSONS TYGER": "home-others",
        "LAGERHAUS ": "home-others",
        "NAKED JUICEBAR": "fika",
        "DECATHLON SVERIGE": "sports",
        "BLOMSTERLANDET": "home-others",
        "ICA SUPERMARKET": "groceries",
        " ICA ": "groceries",
        "COOP ": "groceries",
        "HEMKÖP ": "groceries",
        "NETFLIX.COM": "video-streaming",
        "UBER[ ]+\*TRIP": "taxi",
        "APOTEK HJARTAT": "medicine",
        "AMZN DIGITAL*": "amazon",
        "BROMMAPLANS VARDCENTRA": "medic",
        "KJELL & CO 90": "shopping-misc",
        "ALNAFFIE AB": "home-others",
        "BLOMSTERLANDET": "home-others",
        "CLAS OHLSON": "home-others",
        "AMZN MKTP DE": "amazon",
        "SENSHI SUSHIBAR": "restaurant",
        "BABAS": "restaurant",
        "APOTEK HJARTAT": "medicine",
        "APOTEKET": "medicine",
        "PAYPAL[ ]+\*PATREON": "membership",
        "CDON AB": "shopping-misc",
        "TRESORIT": "cloud-storage",
        "GOOGLE[ ]+\*YOUTUBE MEMBER": "membership",
        "AMIDA KOLGRILL": "restaurant",
        "APOTEA": "medicine",
        "BAUHAUS": "home-others",
        "WIKIPEDIA": "donation",
        "WISE": "charity",
        "BIKESTER": "sports",
        "800 GRADER PIZZA": "restaurant",
        "ARIRANG": "restaurant",
        "LINDEX": "clothes",
        "KANAANS": "fika",
        "RESULTHA TREINOS": "sports",
        "ÅRSAVGIFT": "bills",
        "EXTRAKORTSAVGIFT": "bills",
    #    "": "",
    #    "": "",
    } 

